---
type: yml

httpserver:
  port: 7182

postgres:
  host: 172.20.11.137
  port: 5432
  dbname: traffic

scheduler:
  trafficLenInterval: 30 #second
  modelChangerInterval: 3 #hour
  loadOnlineConfig: 1 #min

grpcserver:
  port: 9090